# Generated by Django 4.0.6 on 2022-07-19 17:28

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True, verbose_name='휴무일')),
                ('closed', models.BooleanField(default=True)),
                ('from_hour', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True)),
                ('to_hour', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='WorkingTime',
            new_name='WeekDayTime',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='holidays',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dept',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=176, size=16, verbose_name='진료과'),
        ),
        migrations.DeleteModel(
            name='SpecialDays',
        ),
        migrations.AddField(
            model_name='weekendtime',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoctor.doctor', verbose_name='의사'),
        ),
    ]
