# Generated by Django 4.0.6 on 2022-07-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydoctor', '0002_weekendtime_rename_workingtime_weekdaytime_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weekdaytime',
            table='weekday',
        ),
        migrations.AlterModelTable(
            name='weekendtime',
            table='weekend',
        ),
    ]
