# Generated by Django 4.0.6 on 2022-07-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoctor', '0004_alter_doctor_non_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdaytime',
            name='weekday_from',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], verbose_name='영업 시작 요일'),
        ),
        migrations.AlterField(
            model_name='weekdaytime',
            name='weekday_to',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], verbose_name='영업 종료 요일'),
        ),
        migrations.AlterField(
            model_name='weekendtime',
            name='holiday',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Saturday'), (7, 'Sunday')], unique=True, verbose_name='휴무일'),
        ),
    ]
