# Generated by Django 4.0.6 on 2022-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoctor', '0005_alter_weekdaytime_weekday_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendtime',
            name='holiday',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Saturday'), (7, 'Sunday')], verbose_name='휴무일'),
        ),
    ]
