# Generated by Django 4.0.6 on 2022-07-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydoctor', '0006_alter_weekendtime_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekdaytime',
            old_name='store',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='weekendtime',
            old_name='store',
            new_name='doctor',
        ),
    ]
