# Generated by Django 4.0.6 on 2022-07-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoctor', '0007_rename_store_weekdaytime_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendtime',
            name='closed',
            field=models.BooleanField(default=True, verbose_name='휴일 유무'),
        ),
        migrations.AlterField(
            model_name='weekendtime',
            name='from_hour',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True, verbose_name='영업 시작 시각'),
        ),
        migrations.AlterField(
            model_name='weekendtime',
            name='holiday',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Saturday'), (7, 'Sunday')], verbose_name='주말 요일'),
        ),
        migrations.AlterField(
            model_name='weekendtime',
            name='to_hour',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True, verbose_name='영업 종료 시각'),
        ),
    ]
