# Generated by Django 4.0.6 on 2022-07-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydoctor', '0008_alter_weekendtime_closed_alter_weekendtime_from_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekdaytime',
            old_name='launch_from',
            new_name='lunch_from',
        ),
        migrations.RenameField(
            model_name='weekdaytime',
            old_name='launch_to',
            new_name='lunch_to',
        ),
    ]
