# Generated by Django 4.0.6 on 2022-07-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoctor', '0010_carerequestlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerequestlist',
            name='book_time',
            field=models.DateTimeField(verbose_name='희망 진료 시각'),
        ),
        migrations.AlterField(
            model_name='carerequestlist',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='진료 요청 수락 여부'),
        ),
    ]
